<a href="https://colab.research.google.com/github/Ruhit43/Assignment2-NLP/blob/main/minEditDistance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
 
def min_edit_dis(target, source):
  #target is the goal word and len(target) number of column
  #source is the main word to be edited and len(source) number of rows
 
  #building matrix
  target = [k for k in target]
  source = [k for k in source]
  matrix = np.zeros((len(source), len(target)))

  #first row and column
  matrix[0] = [j for j in range(len(target))]
  matrix[:,0] = [j for j in range(len(source))]
 
 
  if target[1] != source[1]:
      matrix[1,1] = 2
  
  #through every column
  for c in range(1, len(target)):
      #through every row
      for r in range(1, len(source)):
          #not same letter
          if target[c] != source[r]:
              matrix[r,c] = min(matrix[r-1, c], matrix[r, c-1]) + 1
          #same letter
          else:
              matrix[r,c] = matrix[r-1,c-1]
  return matrix
 
print("Include # before every word input. e.g. #example")
sou = input("Enter source word: ")
tar = input("Enter target word: ")
sol_matrix = min_edit_dis(tar, sou) 
print(sol_matrix)
dis = int(sol_matrix[len(sou)-1][len(tar)-1])
print('Minimum edit distance is: {0}'.format(dis))

Include # before every word input. e.g. #example
Enter source word: #qwert
Enter target word: #qwer
[[0. 1. 2. 3. 4.]
 [1. 0. 1. 2. 3.]
 [2. 1. 0. 1. 2.]
 [3. 2. 1. 0. 1.]
 [4. 3. 2. 1. 0.]
 [5. 4. 3. 2. 1.]]
Minimum edit distance is: 1
